### ISSUE TITLE
[web] I can't clear hive boxes on flutter web

### ISSUE THREAD

**Issue by Macacoazul01** [hivedb/hive#1039]
I'm using hive on more than one project and not being able to clear all the boxes is some sort of a security bug on my context.

Everytime a user logs out the app, the data from the person should be wiped out of the phone/navigator... 

And the ideal way should be deleting all content from the boxes with `Hive.deleteFromDisk();`

Maybe it's related to #1028

Currently using: 
`hive: 2.2.3`
`flutter: 3.0.5`

My flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [versao 10.0.22000.795], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.69.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

Sample project with the error:
[hiveerror.zip](https://github.com/hivedb/hive/files/9163666/hiveerror.zip)

**Comment by Macacoazul01** [comment]
maybe also related to #989

**Comment by Macacoazul01** [comment]
Not sure on which one is the error or if it's in both, like [Techno-Disaster](https://github.com/Techno-Disaster) said that is happening on more platforms than web

`\hive\hive\lib\src\backend\vm\backend_manager.dart`

`\hive\hive\lib\src\backend\js\native\backend_manager.dart`

**Comment by TheOneWithTheBraid** [comment]
Have you got some more logs and stack traces?

**Comment by TheOneWithTheBraid** [comment]
Okay, seems like the bug is caused by missing TupleKeys. I'll quickly place a MR.

**Comment by Macacoazul01** [comment]
@TheOneWithTheBraid is this fix already published on pub?

**Comment by Lorenzobettega** [comment]
@TheOneWithTheBraid I'm with the same error and saw that the bug is already fixed, please can you published this on pub?

**Comment by anilthapa1939** [comment]
is this issue fixed yet? because i am still facing the same issue.
--versions
hive 2.2.3
Flutter 3.3.10

**Comment by Macacoazul01** [comment]
@anilthapa1939 this is maybe on the new dev version

@themisir any expectations on when it'll be released?

**Comment by anilthapa1939** [comment]
> @anilthapa1939 this is maybe on the new dev version
> 
> @themisir any expectations on when it'll be released?

@themisir any update?

**Comment by themisir** [comment]
nope, i am out of loop with this issue and hive web after the latest updates. i can only help with the native implementation, hive web is out of my expertise. is there something that's not been pushed to pub.dev or needs to be fixed?

**Comment by Macacoazul01** [comment]
The #1041 wasn't published yet
